In [1]:
import numpy as np
import pandas as pd
import scipy as sc

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data.shape

(11914, 16)

In [4]:
data.sample(5)

Make         Model  Year  \
4844       Subaru      Forester  2016   
8299   Land Rover   Range Rover  2014   
10255   Chevrolet         Tahoe  2015   
9173         Ford  Shelby GT350  2017   
6206        Dodge       Journey  2016   

                                Engine Fuel Type  Engine HP  Engine Cylinders  \
4844                            regular unleaded      170.0               4.0   
8299   flex-fuel (premium unleaded required/E85)      510.0               8.0   
10255                   flex-fuel (unleaded/E85)      355.0               8.0   
9173              premium unleaded (recommended)      526.0               8.0   
6206                            regular unleaded      283.0               6.0   

      Transmission Type     Driven_Wheels  Number of Doors  \
4844          AUTOMATIC   all wheel drive              4.0   
8299          AUTOMATIC  four wheel drive              4.0   
10255         AUTOMATIC  rear wheel drive              4.0   
9173             MANUAL  rear wheel drive              2.0   
6206          AUTOMATIC   all wheel drive              4.0   

                         Market Category Vehicle Size Vehicle Style  \
4844                           Crossover      Midsize       4dr SUV   
8299   Flex Fuel,Luxury,High-Performance        Large       4dr SUV   
10255              Flex Fuel,Performance        Large       4dr SUV   
9173      Factory Tuner,High-Performance      Midsize         Coupe   
6206                           Crossover      Midsize       4dr SUV   

       highway MPG  city mpg  Popularity    MSRP  
4844            32        24         640   23395  
8299            19        13         258  105300  
10255           23        16        1385   61085  
9173            21        14        5657   54295  
6206            24        16        1851   29795

In [5]:
np.__version__

'1.21.2'

In [6]:
data["Make"].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [16]:
#data["Model"].unique()

In [8]:
audi = data[data["Make"]== "Audi"]#.value_counts()#.tolist()

In [9]:
audi["Model"].nunique()

34

In [10]:
data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [11]:
data.describe(include="all")

Make           Model          Year  Engine Fuel Type  \
count       11914           11914  11914.000000             11911   
unique         48             915           NaN                10   
top     Chevrolet  Silverado 1500           NaN  regular unleaded   
freq         1123             156           NaN              7172   
mean          NaN             NaN   2010.384338               NaN   
std           NaN             NaN      7.579740               NaN   
min           NaN             NaN   1990.000000               NaN   
25%           NaN             NaN   2007.000000               NaN   
50%           NaN             NaN   2015.000000               NaN   
75%           NaN             NaN   2016.000000               NaN   
max           NaN             NaN   2017.000000               NaN   

          Engine HP  Engine Cylinders Transmission Type      Driven_Wheels  \
count   11845.00000      11884.000000             11914              11914   
unique          NaN               NaN                 5                  4   
top             NaN               NaN         AUTOMATIC  front wheel drive   
freq            NaN               NaN              8266               4787   
mean      249.38607          5.628829               NaN                NaN   
std       109.19187          1.780559               NaN                NaN   
min        55.00000          0.000000               NaN                NaN   
25%       170.00000          4.000000               NaN                NaN   
50%       227.00000          6.000000               NaN                NaN   
75%       300.00000          6.000000               NaN                NaN   
max      1001.00000         16.000000               NaN                NaN   

        Number of Doors Market Category Vehicle Size Vehicle Style  \
count      11908.000000            8172        11914         11914   
unique              NaN              71            3            16   
top                 NaN       Crossover      Compact         Sedan   
freq                NaN            1110         4764          3048   
mean           3.436093             NaN          NaN           NaN   
std            0.881315             NaN          NaN           NaN   
min            2.000000             NaN          NaN           NaN   
25%            2.000000             NaN          NaN           NaN   
50%            4.000000             NaN          NaN           NaN   
75%            4.000000             NaN          NaN           NaN   
max            4.000000             NaN          NaN           NaN   

         highway MPG      city mpg    Popularity          MSRP  
count   11914.000000  11914.000000  11914.000000  1.191400e+04  
unique           NaN           NaN           NaN           NaN  
top              NaN           NaN           NaN           NaN  
freq             NaN           NaN           NaN           NaN  
mean       26.637485     19.733255   1554.911197  4.059474e+04  
std         8.863001      8.987798   1441.855347  6.010910e+04  
min        12.000000      7.000000      2.000000  2.000000e+03  
25%        22.000000     16.000000    549.000000  2.100000e+04  
50%        26.000000     18.000000   1385.000000  2.999500e+04  
75%        30.000000     22.000000   2009.000000  4.223125e+04  
max       354.000000    137.000000   5657.000000  2.065902e+06

In [12]:
data["Engine Cylinders"].median()

6.0

In [13]:
data["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [14]:
data["Engine Cylinders"].fillna(4.0, inplace=True)

In [15]:
np.median(np.array(data["Engine Cylinders"]))

6.0

In [19]:
lotus = data[data["Make"] == "Lotus"]

In [20]:
lotus = lotus[["Engine HP", "Engine Cylinders"]]

In [21]:
lotus.duplicated().sum()

20

In [22]:
lotus.drop_duplicates(inplace=True)

In [24]:
lotus.duplicated().sum()

0

In [25]:
lotus.shape

(9, 2)

In [26]:
x = np.array(lotus)

In [27]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [31]:
x.T.shape

(2, 9)

In [32]:
XTX = np.matmul(x.T, x)

In [33]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [34]:
inverse = np.linalg.inv(XTX)

In [35]:
inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [36]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [40]:
z = np.matmul(inverse, x.T)

In [41]:
z

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [44]:
w = z @ y

In [45]:
w

array([  4.59494481, -63.56432501])