In [1]:
# import libraries
import numpy as np
import pandas as pd
import scipy as sc

In [2]:
#read data
data = pd.read_csv("data.csv")

In [3]:
# check shape
# How many records are in the dataset?
data.shape

(11914, 16)

In [4]:
#sample and view
data.sample(5)

Make     Model  Year          Engine Fuel Type  Engine HP  \
9932       Kia  Sportage  2017          regular unleaded      181.0   
9032       GMC    Savana  2016  flex-fuel (unleaded/E85)      285.0   
11295  Hyundai  Veracruz  2010          regular unleaded      260.0   
10008    Dodge   Stratus  2004          regular unleaded      200.0   
9718   Hyundai    Sonata  2015          regular unleaded      185.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
9932                4.0         AUTOMATIC  front wheel drive              4.0   
9032                8.0         AUTOMATIC   rear wheel drive              3.0   
11295               6.0         AUTOMATIC    all wheel drive              4.0   
10008               6.0         AUTOMATIC  front wheel drive              4.0   
9718                4.0         AUTOMATIC  front wheel drive              4.0   

      Market Category Vehicle Size  Vehicle Style  highway MPG  city mpg  \
9932        Crossover      Compact        4dr SUV           29        22   
9032        Flex Fuel      Midsize  Passenger Van           16        11   
11295       Crossover      Midsize        4dr SUV           22        16   
10008             NaN      Midsize          Sedan           26        19   
9718              NaN      Midsize          Sedan           35        24   

       Popularity   MSRP  
9932         1720  22990  
9032          549  36715  
11295        1439  35895  
10008        1851  19690  
9718         1439  23175

In [5]:
# check np version
np.__version__

'1.21.2'

In [6]:
# Who are the most frequent car manufacturers (top-3) according to the dataset?
data["Make"].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [7]:
#data["Model"].unique()

In [8]:
# What's the number of unique Audi car models in the dataset?

audi = data[data["Make"]== "Audi"]#.value_counts()#.tolist()

In [9]:
audi["Model"].nunique()

34

In [10]:
# How many columns in the dataset have missing values?
data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [11]:
# check summary statistics
data.describe(include="all")

Make           Model          Year  Engine Fuel Type  \
count       11914           11914  11914.000000             11911   
unique         48             915           NaN                10   
top     Chevrolet  Silverado 1500           NaN  regular unleaded   
freq         1123             156           NaN              7172   
mean          NaN             NaN   2010.384338               NaN   
std           NaN             NaN      7.579740               NaN   
min           NaN             NaN   1990.000000               NaN   
25%           NaN             NaN   2007.000000               NaN   
50%           NaN             NaN   2015.000000               NaN   
75%           NaN             NaN   2016.000000               NaN   
max           NaN             NaN   2017.000000               NaN   

          Engine HP  Engine Cylinders Transmission Type      Driven_Wheels  \
count   11845.00000      11884.000000             11914              11914   
unique          NaN               NaN                 5                  4   
top             NaN               NaN         AUTOMATIC  front wheel drive   
freq            NaN               NaN              8266               4787   
mean      249.38607          5.628829               NaN                NaN   
std       109.19187          1.780559               NaN                NaN   
min        55.00000          0.000000               NaN                NaN   
25%       170.00000          4.000000               NaN                NaN   
50%       227.00000          6.000000               NaN                NaN   
75%       300.00000          6.000000               NaN                NaN   
max      1001.00000         16.000000               NaN                NaN   

        Number of Doors Market Category Vehicle Size Vehicle Style  \
count      11908.000000            8172        11914         11914   
unique              NaN              71            3            16   
top                 NaN       Crossover      Compact         Sedan   
freq                NaN            1110         4764          3048   
mean           3.436093             NaN          NaN           NaN   
std            0.881315             NaN          NaN           NaN   
min            2.000000             NaN          NaN           NaN   
25%            2.000000             NaN          NaN           NaN   
50%            4.000000             NaN          NaN           NaN   
75%            4.000000             NaN          NaN           NaN   
max            4.000000             NaN          NaN           NaN   

         highway MPG      city mpg    Popularity          MSRP  
count   11914.000000  11914.000000  11914.000000  1.191400e+04  
unique           NaN           NaN           NaN           NaN  
top              NaN           NaN           NaN           NaN  
freq             NaN           NaN           NaN           NaN  
mean       26.637485     19.733255   1554.911197  4.059474e+04  
std         8.863001      8.987798   1441.855347  6.010910e+04  
min        12.000000      7.000000      2.000000  2.000000e+03  
25%        22.000000     16.000000    549.000000  2.100000e+04  
50%        26.000000     18.000000   1385.000000  2.999500e+04  
75%        30.000000     22.000000   2009.000000  4.223125e+04  
max       354.000000    137.000000   5657.000000  2.065902e+06

In [12]:
# find medain
data["Engine Cylinders"].median()

6.0

In [13]:
# calculate the most frequent value of the same "Engine Cylinders"
data["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [14]:
#Use the fillna method to fill the missing values in "Engine Cylinders" 
#with the most frequent value from the previous step.
data["Engine Cylinders"].fillna(4.0, inplace=True)

In [15]:
# Now, calculate the median value of "Engine Cylinders" once again.
np.median(np.array(data["Engine Cylinders"]))

6.0

# Question 7

1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Invert XTX.
6. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the first element of w?

In [16]:
lotus = data[data["Make"] == "Lotus"]

In [17]:
lotus = lotus[["Engine HP", "Engine Cylinders"]]

In [18]:
lotus.duplicated().sum()

20

In [19]:
lotus.drop_duplicates(inplace=True)

In [20]:
lotus.duplicated().sum()

0

In [21]:
lotus.shape

(9, 2)

In [22]:
x = np.array(lotus)

In [23]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [24]:
x.T.shape

(2, 9)

In [25]:
XTX = np.matmul(x.T, x)

In [26]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [27]:
inverse = np.linalg.inv(XTX)

In [28]:
inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [29]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [30]:
z = np.matmul(inverse, x.T)

In [31]:
z

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [32]:
w = z @ y

In [33]:
w

array([  4.59494481, -63.56432501])